apiVersion: v1
data:
    token: ENC[AES256_GCM,data:u8eY5s8VNriOom+d1t6WhQGqWK3oEtHqtVs+mOT6TQVaLXUzN4kR74fJnFFIXRMw,iv:ns/ff8pW4azMExeuYpMavJ04A5RfK8+LbTuuIRbApZY=,tag:llFmTMVCK7x9vFRh68DvkQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: app-secret
    namespace: myapp
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-07-25T18:02:25Z"
    mac: ENC[AES256_GCM,data:DEFoK9gWzh6Ca4RYeI+p9USz+dZp9xmRN73lF3EwLo/xoKG9TuZKQcd6Vk4CJMrC1ae1nS/pXeifuZuvWtvs0XQsG28LL0ru2L3Aa96Lt6a+VL98IDwahmH1wugm5oweYs6wcNaskmvm2r0F94wwKSrPUkRNhOsEz5InfMKndp4=,iv:BTNOR0TK8okcYFxz0ECMaFpVDwKpWzLA+f485vFTpf4=,tag:/gmunpTTaoxaZcl/+7lX0Q==,type:str]
    pgp:
        - created_at: "2024-07-25T18:02:25Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAyUpShfNkFB/AQf/RNNbYMw9Uv1hZ56ReKCeDA099E5lZLss5gemf4jSdiRU
            +8B1CeYZXOhDQ5eUT+lLaDJFAjdCfeNXfA8czVBzRHHTFuX5FZskgI6Ta5ReoBbE
            MW/MtWToCeLc4A7HAmAMnPvFBM6YkWizCAc1aG/MYPf5+iagkRP95KT74m0mIzaw
            5dpPVV6UKFa3y/QajWd4CRircGNR8Edk4YXy+0FWGkhJcdOP73GzDvwUTVnRwgxt
            KbcPmyjEIqD8BEEHGCKdAHQwThhKlUiGmtLLQkVXarkZs1tmlyhQVaFl2EBSZCEL
            3qN43gS8k1bCwJRPoZtJLBQeTs1NxVnHbgeamrOgt9JeARQs1HxT2nZFMGsI+GWN
            QP0Psb4YnqKsqOWN9vIkKnki00uUpkFFr44/JkMc4pxl5ci2FLUbTz6JI1pw3aVn
            HWYUgIQMzp6GvcN2sB4hrRG3CCamJBMGQqSZXA9I0g==
            =rb5h
            -----END PGP MESSAGE-----
          fp: FBC7B9E2A4F9289AC0C1D4843D16CEE4A27381B4
    unencrypted_regex: ^(apiVersion|metadata|kind|type)$
    version: 3.9.0
